### ISSUE TITLE
Dependency Cycle

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs-cmds#18]
This package absolutely **MUST NOT** depend on go-ipfs.

Currently, if I try to update cmdkit, I get failures because go-ipfs uses a different version of go-ipfs-cmdkit (and we leave go-ipfs gx-rewritten). However, I can't update go-ipfs-cmdkit in go-ipfs without updating it here first (because they *both* depend on go-ipfs-cmdkit).

I *can* just update this, break the tests, update go-ipfs, and then re-test but *that's* not something we should be doing.

**Comment by keks** [comment]
I don't think this is a dependency cycle, looks more like a "half-diamond-problem" to me (a->b->c and a->c). I agree though that all dependencies to go-ipfs must be removed to make this a proper, self-sustaining package.

I'm currently working on the next round of refactor in the cmds3.0 branches (go-ipfs{,-cmds,-cmdkit}). There I moved all the legacy code to a legacy subpackage, which still depends on go-ipfs. go-ipfs-cmds will not depend on the legacy package, though. Here's a sketch of the dep tree:

```
go-ipfs/... -> go-ipfs-cmdkit
go-ipfs/... -> go-ipfs-cmds/...
go-ipfs-cmds/... -> go-ipfs-cmdkit
go-ipfs-cmds/legacy -> go-ipfs-cmds
go-ipfs-cmds/http -> go-ipfs-cmds
go-ipfs-cmds/cli -> go-ipfs-cmds
```
After that refactor I would like to start porting more ipfs commands to go-ipfs-cmds instead of go-ipfs/commands, so that we can at some point in the not-so-distant future get rid of the legacy subpackage.

Does that make sense to you?

**Comment by keks** [comment]
Trying to test myself, I see what you mean with dependency cycle. But, like I said, I'm working on it and hope to get it into review this month.

**Comment by Stebalien** [comment]
What are we using the legacy adapter for? Can we just move away from it?

**Comment by keks** [comment]
Sorry, I should have provided more context. Most of go-ipfs/core/commands still uses the API of go-ipfs/commands. We didn't want to move all commands at once because that would likely have been too big of a change. Notable commands that use the new API are add, cat, pubsub, and some of the stat stuff.
So we will be able to move away from legacy once we moved all commands to the new API. I still want to make a few pretty big changes to the new API, so I'm hesitant to change them now. I definitely want legacy to go as soon as possible, but I first want to make the new API good. To track the progress of this, I created #21.

**Comment by Stebalien** [comment]
Got it. However, won't moving the legacy API out into a different package not fix anything? Won't it *still* depend on go-ipfs? Should we just move that part *back* into go-ipfs?

**Comment by keks** [comment]
Oh yes, another thing I forgot to mention.

In cmds3.0 I'm putting the burden of converting the `"go-ipfs/commands".Command` to a `"go-ipfs-cmds".Command` on the caller. That means that go-ipfs-cmds does not know about old commands anymore. If you want to add an oldschool subcommand to your newschool command, you would have to
```go
// in core/commands:
var cmd = &cmds.Command{
  Subcommands: map[string]*cmds.Command{
    "old-timey": legacy.NewCommand(&oldcmds.Command{
      Helptext: "does the old-timey dance",
      Run: func(req oldcmds.Request, res oldcmds.Response) { /* ... */ },
      // ...
    }),
  },
}

// in legacy:
func NewCommand(cmd *oldcmds.Command) *cmds.Command { // ...
```

That way we end up with no links to any go-ipfs repo.

Also - while the ipfs-specific Context struct at the moment is annoying, at least it only imports go-ipfs/{core, repo/config} and not go-ipfs/commands, avoiding a dependency cycle.

**Comment by keks** [comment]
I think this is resolved.
